[package]
name = "orbite"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
rand = "0.7.0"
rayon = "1.1"
rust-ini = "0.13"
rand_distr = "*"
kiss3d = "0.22.1"
nalgebra = "0.19.0"
csv = "1.1.1"